version: 0.2

phases:
    install:
      java: corretto11
    pre_build:
      commands:
        - echo "Entered into Pre-Build Stage..."
        - echo "Cleaning the previous build..."
        - aws ecr get-login-password --region AWS_REGION | docker login --username AWS --password-stdin REPOSITORY_URL
        - mvn clean
        - echo "Pre-Build Stage Complete..."
    build:
      commands:
        - echo "Entered into Build Stage..."
        - echo "Building Package"
        - mvn test
        - mvn package
        - echo "Build Stage Completed..."
        - docker build -t $REPOSITORY_URI:latest .
        - docker push $REPOSITORY_URI:latest
artifacts:
      files:
        - '**/*'
